<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{19c7fd4e-92ee-4c48-b527-6576c9627f78}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbLogging:			Tc3_Event.FB_LoggingProvider;
	fbLogger:			Tc3_Event.FB_Logger;
	fbFileLogger:		Tc3_Event.FB_FileLogger;
	fbTest:				FB_TestSlow;
  	exception:			__SYSTEM.ExceptionCode;	
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[
__TRY
	
	fbLogging.M_Add(fbLogger);
	fbLogging.M_Add(fbFileLogger);
	
	fbLogger();
	fbFileLogger(sPathName:= 'C:\temp\log.txt');
	
	fbTest.P_Event.P_Logger:= fbLogging;
	
	fbTest();

__CATCH(exception)


__ENDTRY]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>