<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Message" Id="{84167246-7318-466e-9219-bf236e6d60e2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Message
VAR_INPUT
	eLogLevel:			E_LogLevel;
	nID:				UDINT;
	nTimestamp:			ULINT;	
	sSource:			STRING(255);
	sType:				STRING(255);
	sMessage:			STRING(255);
	sDefault:			STRING(255);
	sArguments:			STRING(255);
	bRaised:			BOOL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>